### ISSUE TITLE
I'm having compatibility issues while running.

### ISSUE THREAD

**Issue by knightlyf** [dakshtrehan/Image-Captioning-Bot#1]
Encountered the following Error 
File "D:\Anaconda\envs\img\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node model/conv1_conv/Conv2D (defined at prog.py:144) ]] [Op:__inference_predict_function_8041]

Im running this on 
GTX 1050 
i5 7300HQ
8GB RAM
python 3.6
cudatoolkit v 10.2.89
cudnn 7.6.5

**Comment by dakshtrehan** [comment]
I think you're using the wrong version of TF. 
Kindly update.

**Comment by knightlyf** [comment]
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

adding this to the code  fixed the issue thanx a bunch

**Comment by dakshtrehan** [comment]
Happy you got the issue resolved!
